# Generated by Django 3.2.6 on 2021-08-06 19:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
