# Generated by Django 3.2.6 on 2021-08-07 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_task_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_content',
        ),
    ]
